### ISSUE TITLE
Website installation: error with Nodejs

### ISSUE THREAD

**Issue by Jnsll** [diverse-team/diverse-team.github.io#33]
While following the readme file on the ```refactoring``` branch for the installation to run the website on my local machine, I have an error at the step 4 when doing ```npm run fetchall```.

The error message: ```npm ERR! missing script: fetchall```. With a log file containing the following information:
```0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/bin/npm', 'run', 'fetchall' ]
2 info using npm@6.14.3
3 info using node@v13.11.0
4 verbose stack Error: missing script: fetchall
4 verbose stack     at run (/usr/lib/node_modules/npm/lib/run-script.js:155:19)
4 verbose stack     at /usr/lib/node_modules/npm/lib/run-script.js:63:5
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:116:5
4 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:436:5
4 verbose stack     at checkBinReferences_ (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:391:45)
4 verbose stack     at final (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:434:3)
4 verbose stack     at then (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:161:5)
4 verbose stack     at ReadFileContext.<anonymous> (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:350:20)
4 verbose stack     at ReadFileContext.callback (/usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:115:16)
4 verbose stack     at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:261:13)
5 verbose cwd /DATA/These/Projects/diverse-team.github.io/tools
6 verbose Linux 5.4.27-1-MANJARO
7 verbose argv "/usr/bin/node" "/bin/npm" "run" "fetchall"
8 verbose node v13.11.0
9 verbose npm  v6.14.3
10 error missing script: fetchall
11 verbose exit [ 1, true ] ```.

**Comment by oscarlvp** [comment]
Yes, sorry. Feature documented but not implemented :)
Should be fine now.
Close the issue once it works on your side.

**Comment by Jnsll** [comment]
Okay thanks, no problem. Works perfectly now, installation done without any problem. :+1:
